### ISSUE TITLE
All containers report updates available when there are no updates available

### ISSUE THREAD

**Issue by brianp** [tari-project/tari-launchpad#104]
I've spent a bunch of time futzing with docker and this issue over the last couple of weeks. As an interim band-aid, I've opened a PR to turn off the update notifications.

Currently, we have a shell of the feature. The UX is there, we can communicate to quay.io but that's all we're doing. After that, we're returning static values that say we always need to update. I added a communication with DockerHub similar to the quay.io service so all images could fetch data about their latest tags. This presented the next set of issues. DockerHub and the Docker cli don't generate sha hashes of the images in the same method. As a result we can't compare or validate that an image we just downloaded is the image it claims to be. There is a manfiest file we can fetch for a tag that should contain all the platform specific shas for images but we'll have to introduce extra checks for the platform we're on, and on top of that I've still found some manifest files don't contain *any* matching shas to the local images. So it's not guaranteed to work anyway.

We could do comparisons by image created at timestamps but we'll still have to query and break down the results by platform to find if the platform specific image has been updated, and not the an image for a different platform on the same tag.

All this to say it ended up being slightly larger than a small bug fix, and a little more consideration is needed to get the original desired results.

**Comment by CjS77** [comment]
This is no longer the case.

The contrapositive must be checked though.
