### ISSUE TITLE
Miner UI doesn't reflect won blocks

### ISSUE THREAD

**Issue by brianp** [tari-project/tari-launchpad#108]
The miner has successfully won blocks as the wallet shows:

![Image](https://user-images.githubusercontent.com/179134/182868050-952ad038-df08-4496-9052-6425ed74d36d.png)

but fails to show the value won on the miner page:

![Image](https://user-images.githubusercontent.com/179134/182868174-8fabd44b-e699-4771-9c0f-9e04b6d9d1c4.png)

**Comment by CjS77** [comment]
Miner balance does indicate coins won (per session)
