### ISSUE TITLE
[Settings] Security Settings (seed phrase)

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#11]
- get password seed phrase from backend
- show to user
- verify
- let them print
- to show "created" state - we need to either remember we already set it up or get that information from backend

**Comment by NovaT82** [comment]
#### CjS77 commented:

Do you mean the seed phrase for the wallet?

**Comment by NovaT82** [comment]
#### tarnas14 commented:

@CjS77  yes, updated description

**Comment by NovaT82** [comment]
#### CjS77 commented:

I strongly suggest that we never expose the seed phrase via gRPC. It's too much of a security risk.

**Comment by NovaT82** [comment]
#### CjS77 commented:

Exposing it via a standard `tauri::command` should be ok though.

**Comment by brianp** [comment]
Completed [here](https://github.com/Altalogy/tari/pull/407)
