### ISSUE TITLE
"You earned Tari" in Transaction history didn't appear for the first ~30 won blocks

### ISSUE THREAD

**Issue by brianp** [tari-project/tari-launchpad#115]
I did not realize this was an item in the transaction history. I had won about 30 blocks before the first one appeared.

![Image](https://user-images.githubusercontent.com/179134/187660453-dce46934-9d31-477c-add3-10a820aec218.png)

**Comment by CjS77** [comment]
Closing this, as the messaging system has been completely reworked.
