### ISSUE TITLE
[Random] check if offline and tell the user

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#16]
[figma](https://www.figma.com/file/adOeOi2kRKn8mKM8GsrwZh/Tari-Launchpad-(Altalogy-Copy)?node-id=406%3A42759)

**Comment by NovaT82** [comment]
#### tarnas14 commented:

ping something on the internet?
periodically?

could this be a part of healthcheck for containers ?
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine ?

**Comment by brianp** [comment]
Duplicate of https://github.com/tari-project/tari-launchpad/issues/92
