### ISSUE TITLE
Setup logging

### ISSUE THREAD

**Issue by brianp** [tari-project/tari-launchpad#163]
We don't have a good way to access or view container logs.

Review the original plans for logging.

Potentially setup grafana / loki / promtail defaults?

**Comment by CjS77** [comment]
Yes, setting up grafana defaults are the way to go.

Loki and promtail are already configured to consume logs, unless something has changed.
We need to include a Grafana view onto the logs and package it with the default tauri build

**Comment by CjS77** [comment]
Logging is functional on the backend now
