### ISSUE TITLE
Tari app statup command isn't accepting extra arguments

### ISSUE THREAD

**Issue by brianp** [tari-project/tari-launchpad#174]
After YOLO'ing [this PR](https://github.com/tari-project/tari-launchpad/pull/171) the new containers no longer accept additional arguments on startup. #171 did fix the issue it set out to, but has now caused this new problem.

LaunchPad builds up a set of special arguments that get passed on docker container startup. Previously they were passed fine and received by tari apps.

**Comment by leet4tari** [comment]
Tried quite a few different ways to address this, but the basics are, if we want shell substitution in the docker ```entrypoint```, we can't really use command override as just an argument addition to the entrypoint.  
  
I think that the env ```APP_NAME``` in entrypoint was only really used as a common place to start the correct application executable.  This env is been set by the docker build, no need to pass at start-up.  
  
https://github.com/tari-project/tari-launchpad/pull/178 should remove the literal usage of ```${APP_NAME}```
