### ISSUE TITLE
RUSTSEC-2021-0060: `aes-soft` has been merged into the `aes` crate

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#29]
> `aes-soft` has been merged into the `aes` crate

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `aes-soft`                      |
| Version             | `0.6.4`                   |
| URL                 | [https://github.com/RustCrypto/block-ciphers/pull/200](https://github.com/RustCrypto/block-ciphers/pull/200) |
| Date                | 2021-04-29                         |

Please use the `aes` crate going forward. The new repository location is at:

&lt;https://github.com/RustCrypto/block-ciphers/tree/master/aes&gt;

AES-NI is now autodetected at runtime on `i686`/`x86-64` platforms.
If AES-NI is not present, the `aes` crate will fallback to a constant-time
portable software implementation.

To force the use of a constant-time portable implementation on these platforms,
even if AES-NI is available, use the new `force-soft` feature of the `aes`
crate to disable autodetection.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2021-0060.html) for additional details.

**Comment by brianp** [comment]
Closing as I can't find this dependency in the app.
