### ISSUE TITLE
Tari container - wallet password is not updated until the app restart

### ISSUE THREAD

**Issue by CjS77** [tari-project/tari-launchpad#3]
The container does not use the newly passed wallet password, until the application is restarted.

It affects all environment variables of all containers, ie. data_folder, monero urls, etc.

**Comment by brianp** [comment]
@CjS77 was there any more specifics on this. I haven't recreated any kind of bug while playing with the containers and am tempted to close this for now.

**Comment by CjS77** [comment]
With a recent build it looks like the password is not propagated to the wallet creation.

1. Start a clean build
2. Create wallet with password "tari"
3. Sync blockchain, mine etc
4. Restart launchpad
5. Wallet claims "tari" is not the valid password
6. On investigation, the password was actually "" (blank)

**Comment by CjS77** [comment]
No longer needed
