### ISSUE TITLE
RUSTSEC-2021-0059: `aesni` has been merged into the `aes` crate

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#30]
> `aesni` has been merged into the `aes` crate

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `aesni`                      |
| Version             | `0.10.0`                   |
| URL                 | [https://github.com/RustCrypto/block-ciphers/pull/200](https://github.com/RustCrypto/block-ciphers/pull/200) |
| Date                | 2021-04-29                         |

Please use the `aes` crate going forward. The new repository location is at:

&lt;https://github.com/RustCrypto/block-ciphers/tree/master/aes&gt;

AES-NI is now autodetected at runtime on `i686`/`x86-64` platforms.
If AES-NI is not present, the `aes` crate will fallback to a constant-time
portable software implementation.

To prevent this fallback (and have absence of AES-NI result in an illegal
instruction crash instead), continue to pass the same RUSTFLAGS which were
previously required for the `aesni` crate to compile:

```
RUSTFLAGS=-Ctarget-feature=+aes,+ssse3
```

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2021-0059.html) for additional details.

**Comment by brianp** [comment]
Closing as I can't find this dependency in the app.
