### ISSUE TITLE
RUSTSEC-2021-0064: `cpuid-bool` has been renamed to `cpufeatures`

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#31]
> `cpuid-bool` has been renamed to `cpufeatures`

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `cpuid-bool`                      |
| Version             | `0.2.0`                   |
| URL                 | [https://github.com/RustCrypto/utils/pull/381](https://github.com/RustCrypto/utils/pull/381) |
| Date                | 2021-05-06                         |

Please use the `cpufeatures`` crate going forward:

&lt;https://github.com/RustCrypto/utils/tree/master/cpufeatures&gt;

There will be no further releases of `cpuid-bool`.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2021-0064.html) for additional details.

**Comment by brianp** [comment]
Closing as I can't find this dependency in the app.
