### ISSUE TITLE
RUSTSEC-2020-0016: `net2` crate has been deprecated; use `socket2` instead

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#32]
> `net2` crate has been deprecated; use `socket2` instead

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `net2`                      |
| Version             | `0.2.37`                   |
| URL                 | [https://github.com/deprecrated/net2-rs/commit/3350e3819adf151709047e93f25583a5df681091](https://github.com/deprecrated/net2-rs/commit/3350e3819adf151709047e93f25583a5df681091) |
| Date                | 2020-05-01                         |

The [`net2`](https://crates.io/crates/net2) crate has been deprecated
and users are encouraged to considered [`socket2`](https://crates.io/crates/socket2) instead.

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2020-0016.html) for additional details.

**Comment by brianp** [comment]
Closing as I can't find this dependency in the app.
