### ISSUE TITLE
RUSTSEC-2018-0017: `tempdir` crate has been deprecated; use `tempfile` instead

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#35]
> `tempdir` crate has been deprecated; use `tempfile` instead

| Details             |                                                |
| ------------------- | ---------------------------------------------- |
| Status              | unmaintained                |
| Package             | `tempdir`                      |
| Version             | `0.3.7`                   |
| URL                 | [https://github.com/rust-lang-deprecated/tempdir/pull/46](https://github.com/rust-lang-deprecated/tempdir/pull/46) |
| Date                | 2018-02-13                         |

The [`tempdir`](https://crates.io/crates/tempdir) crate has been deprecated
and the functionality is merged into [`tempfile`](https://crates.io/crates/tempfile).

See [advisory page](https://rustsec.org/advisories/RUSTSEC-2018-0017.html) for additional details.

**Comment by brianp** [comment]
Closing as I can't find this dependency in the app.
