### ISSUE TITLE
[Onboarding] Splash screen w/Tari disco ball

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#45]
From #22 

- Create splash screen with Tari spinning loop video

![Screen Recording 2022-06-09 at 12 32 03](https://user-images.githubusercontent.com/69508715/172827407-c4d3492b-f5bb-4952-a996-e639a7447d89.gif)

<img width="479" alt="image" src="https://user-images.githubusercontent.com/69508715/172827574-c54d3a5a-315c-48d4-a665-18e173825c55.png">

**Comment by brianp** [comment]
Issue is complete.
