### ISSUE TITLE
Tauri doesn't work on Windows

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#46]
**Development**

The Tari Launchpad starts successfully on Windows, but starting container crashes the app with the following error:

```
thread 'main' has overflowed its stack
error: process didn't exit successfully: `project_dir\tari\target\debug\tari_launchpad.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

```

**Release**

The Tari Launchpad start successfully and can run Tor container, but BaseNode container exits with error:

```
exec /usr/bin/start_tari_app.sh: no such file or directory
```

## Steps to reproduce

1. install dependencies and start Launchpad:

```
$ cd applications/launchpad
$ yarn install
$ cd gui-react
$ yarn install
$ cd ..
$ yarn tauri dev
```

2. Tari Launchpad should start successfully
3. Open `Expert view` and start `Tor`
4. Launchpad crashes and gives above error in terminal.

## Notes

1. Installed `randomx-rs` required dependencies
2. Tried to use rustc `1.61.0` (changed in `rust-toolchain.toml`)

**Comment by NovaT82** [comment]
#### tarnas14 commented:

related to #325 and #324

**Comment by brianp** [comment]
Update on this. I successfully built a dev environment in a windows vm, but docker has an issue virtualizing unix, in a virtualized windows, on macos (go figure). As a result I can't actually get to the core path/permission windows related problems for testing.
