### ISSUE TITLE
[BaseNode]: QR content

### ISSUE THREAD

**Issue by NovaT82** [tari-project/tari-launchpad#68]
Replace the hard-coded content of Base Node QR content.

**Comment by NovaT82** [comment]
#### CjS77 commented:

@tomaszantas FYI..

The deep link schema is discussed on the [Tari RFC site](https://rfc.tari.com/RFC-0154_DeepLinksConvencion.html).

There's also an [example of it in action](https://github.com/tari-project/wallet-ios/blob/development/MobileWallet/Common/Deep%20Links/DeeplinkHandler.swift).

**Comment by NovaT82** [comment]
#### tomaszantas commented:

Waiting for #379

**Comment by brianp** [comment]
Closing this as the QR code works and pulls the content from the running container/active base node.
